import { RoomConfig, RoomId } from '../types';

export const ROOMS: Record<RoomId, RoomConfig> = {
  consultorio_01: {
    id: 'consultorio_01',
    name: 'Consultório 01',
    subname: 'Clínico Geral',
    description: 'Atendimento Clínico, Triagem Médica e Consultas Gerais',
    category: 'clinico',
    prefix: 'CLI',
    colorName: 'blue',
    bgLight: 'bg-blue-50',
    borderLight: 'border-blue-200',
    textDark: 'text-blue-900',
    badgeBg: 'bg-blue-600',
    badgeText: 'text-white',
    glowColor: 'rgba(37, 99, 235, 0.4)',
    defaultDoctor: 'Dr. Roberto Silveira (Clínico)',
    soundType: 'clinico',
    icon: 'Stethoscope'
  },
  consultorio_02: {
    id: 'consultorio_02',
    name: 'Consultório 02',
    subname: 'Especialidades Médicas',
    description: 'Cardiologia, Dermatologia, Ortopedia e Especialistas',
    category: 'especialidade',
    prefix: 'ESP',
    colorName: 'violet',
    bgLight: 'bg-purple-50',
    borderLight: 'border-purple-200',
    textDark: 'text-purple-900',
    badgeBg: 'bg-purple-600',
    badgeText: 'text-white',
    glowColor: 'rgba(147, 51, 234, 0.4)',
    defaultDoctor: 'Dra. Mariana Vasconcelos (Cardiologia)',
    soundType: 'especialidade',
    icon: 'Sparkles'
  },
  medicacao: {
    id: 'medicacao',
    name: 'Sala de Medicação',
    subname: 'Enfermagem & Procedimentos',
    description: 'Administração de Injetáveis, Curativos e Observação',
    category: 'medicacao',
    prefix: 'MED',
    colorName: 'amber',
    bgLight: 'bg-amber-50',
    borderLight: 'border-amber-200',
    textDark: 'text-amber-900',
    badgeBg: 'bg-amber-600',
    badgeText: 'text-white',
    glowColor: 'rgba(217, 119, 6, 0.4)',
    defaultDoctor: 'Enfª. Camila Duarte (Enfermagem)',
    soundType: 'medicacao',
    icon: 'Syringe'
  },
  odonto_01: {
    id: 'odonto_01',
    name: 'Odontológico 01',
    subname: 'Odontologia Geral & Estética',
    description: 'Restaurações, Profilaxia, Ortodontia e Avaliações',
    category: 'odonto',
    prefix: 'OD1',
    colorName: 'teal',
    bgLight: 'bg-teal-50',
    borderLight: 'border-teal-200',
    textDark: 'text-teal-900',
    badgeBg: 'bg-teal-600',
    badgeText: 'text-white',
    glowColor: 'rgba(13, 148, 136, 0.4)',
    defaultDoctor: 'Dr. Lucas Ferreira (Cirurgião Dentista)',
    soundType: 'odonto1',
    icon: 'Smile'
  },
  odonto_02: {
    id: 'odonto_02',
    name: 'Odontológico 02',
    subname: 'Cirurgia & Endodontia',
    description: 'Tratamentos de Canal, Extrações e Implantes',
    category: 'odonto',
    prefix: 'OD2',
    colorName: 'cyan',
    bgLight: 'bg-cyan-50',
    borderLight: 'border-cyan-200',
    textDark: 'text-cyan-900',
    badgeBg: 'bg-cyan-700',
    badgeText: 'text-white',
    glowColor: 'rgba(14, 116, 144, 0.4)',
    defaultDoctor: 'Dra. Beatriz Mendes (Endodontista)',
    soundType: 'odonto2',
    icon: 'ShieldCheck'
  }
};

export const ROOM_LIST = Object.values(ROOMS);
