import { User } from '../types';

export const DEFAULT_USERS: User[] = [
  {
    id: 'usr-admin',
    name: 'Administrador da Clínica',
    username: 'admin',
    password: '123',
    role: 'admin',
    specialty: 'Gestão Hospitalar & Coordenação',
    assignedRoomId: 'all',
    email: 'admin@medifila.com.br',
    phone: '(11) 98765-4321',
    active: true,
    createdAt: '2026-01-01T08:00:00.000Z',
    avatarBg: 'bg-blue-600'
  },
  {
    id: 'usr-dr-roberto',
    name: 'Dr. Roberto Silveira',
    username: 'dr.roberto',
    password: '123',
    role: 'medico',
    councilType: 'CRM',
    councilNumber: '142.890/SP',
    specialty: 'Clínica Geral & Atendimento Primário',
    assignedRoomId: 'consultorio_01',
    email: 'dr.roberto@medifila.com.br',
    phone: '(11) 97123-4567',
    active: true,
    createdAt: '2026-01-15T08:00:00.000Z',
    avatarBg: 'bg-blue-600'
  },
  {
    id: 'usr-dra-mariana',
    name: 'Dra. Mariana Vasconcelos',
    username: 'dra.mariana',
    password: '123',
    role: 'medico',
    councilType: 'CRM',
    councilNumber: '189.442/SP',
    specialty: 'Cardiologia & Especialidades',
    assignedRoomId: 'consultorio_02',
    email: 'dra.mariana@medifila.com.br',
    phone: '(11) 97890-1234',
    active: true,
    createdAt: '2026-02-01T08:00:00.000Z',
    avatarBg: 'bg-purple-600'
  },
  {
    id: 'usr-enf-camila',
    name: 'Enfª. Camila Duarte',
    username: 'enf.camila',
    password: '123',
    role: 'enfermeiro',
    councilType: 'COREN',
    councilNumber: '321.654/SP',
    specialty: 'Enfermagem Clínica & Procedimentos',
    assignedRoomId: 'medicacao',
    email: 'enf.camila@medifila.com.br',
    phone: '(11) 98321-6549',
    active: true,
    createdAt: '2026-02-10T08:00:00.000Z',
    avatarBg: 'bg-amber-600'
  },
  {
    id: 'usr-dr-lucas',
    name: 'Dr. Lucas Ferreira',
    username: 'dr.lucas',
    password: '123',
    role: 'dentista',
    councilType: 'CRO',
    councilNumber: '45.123/SP',
    specialty: 'Odontologia Geral & Estética',
    assignedRoomId: 'odonto_01',
    email: 'dr.lucas@medifila.com.br',
    phone: '(11) 99123-8877',
    active: true,
    createdAt: '2026-02-15T08:00:00.000Z',
    avatarBg: 'bg-emerald-600'
  },
  {
    id: 'usr-dra-beatriz',
    name: 'Dra. Beatriz Mendes',
    username: 'dra.beatriz',
    password: '123',
    role: 'dentista',
    councilType: 'CRO',
    councilNumber: '58.789/SP',
    specialty: 'Cirurgia Odontológica & Endodontia',
    assignedRoomId: 'odonto_02',
    email: 'dra.beatriz@medifila.com.br',
    phone: '(11) 99456-1122',
    active: true,
    createdAt: '2026-03-01T08:00:00.000Z',
    avatarBg: 'bg-cyan-600'
  },
  {
    id: 'usr-recepcao',
    name: 'Ana Paula Rocha',
    username: 'recepcao',
    password: '123',
    role: 'recepcao',
    specialty: 'Recepção, Triagem & Emissão de Senhas',
    assignedRoomId: 'all',
    email: 'recepcao@medifila.com.br',
    phone: '(11) 98111-2233',
    active: true,
    createdAt: '2026-01-05T08:00:00.000Z',
    avatarBg: 'bg-blue-500'
  },
  {
    id: 'usr-tv-painel',
    name: 'Totem Sala de Espera (TV)',
    username: 'painel.tv',
    password: '123',
    role: 'painel_tv',
    specialty: 'Exibição Visual de Senhas e Chamadas em TV',
    assignedRoomId: 'all',
    active: true,
    createdAt: '2026-01-01T08:00:00.000Z',
    avatarBg: 'bg-indigo-600'
  }
];
